package org.jbpm.solution.rewards;

import org.jbpm.examples.rewards.EmployeeReward;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EmployeeReward extends EmployeeReward implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Position(value = 0)
   private java.lang.Boolean pmAck;
   @org.kie.api.definition.type.Position(value = 1)
   private java.lang.Boolean hrAck;
   @org.kie.api.definition.type.Position(value = 2)
   private java.util.Date effectiveDate;

   public java.lang.Boolean getPmAck()
   {
      return this.pmAck;
   }

   public void setPmAck(java.lang.Boolean pmAck)
   {
      this.pmAck = pmAck;
   }

   public java.lang.Boolean getHrAck()
   {
      return this.hrAck;
   }

   public void setHrAck(java.lang.Boolean hrAck)
   {
      this.hrAck = hrAck;
   }

   public java.util.Date getEffectiveDate()
   {
      return this.effectiveDate;
   }

   public void setEffectiveDate(java.util.Date effectiveDate)
   {
      this.effectiveDate = effectiveDate;
   }

   public EmployeeReward()
   {
   }

   public EmployeeReward(java.lang.Boolean pmAck, java.lang.Boolean hrAck,
         java.util.Date effectiveDate)
   {
      this.pmAck = pmAck;
      this.hrAck = hrAck;
      this.effectiveDate = effectiveDate;
   }

}