package org.jbpm.examples.rewards;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EmployeeReward implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public EmployeeReward() {
    }

}